
# global settings
dnsSuffix: 3eaf3a8cd0b54691a700.eastus2.aksapp.io

# API settings
apiReplicas: 2
apiVersion: latest
apiPort: 80
apiDnsName: api

# Portal settings
portalReplicas: 2
portalVersion: latest
portalPort: 80
portalDnsName: portal