apiVersion: apps/v1
kind: Deployment
metadata:
  name: azupgportal-api
spec:
  replicas: {{.Values.api.replicas}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: azupgportal-api
  template:
    metadata:
      labels:
        app: azupgportal-api
    spec:
      containers:
      - name: azupgportal-api
        image: azupgportal.azurecr.io/plasne/azure-upgrade-portal:{{.Values.api.version}}
        ports:
        - containerPort: {{.Values.api.port}}
          name: http
        env:
        - name: PORT
          value: '{{.Values.api.port}}'
      imagePullSecrets:
      - name: azupgportal-registry
---
apiVersion: v1
kind: Service
metadata:
  name: azupgportal-api
spec:
  type: ClusterIP
  ports:
  - port: {{.Values.api.port}}
    protocol: TCP
  selector:
    app: azupgportal-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: azupgportal-api
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: {{.Values.api.dns-name}}.{{.Values.dns-suffix}}
    http:
      paths:
      - backend:
          serviceName: azupgportal-api
          servicePort: {{.Values.api.port}}
        path: /